name: check

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Enable FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: nix flake check
        run: nix flake check --print-build-logs

      - name: build kakapo toplevel
        run: |
          nix build --print-build-logs --no-link \
            .#nixosConfigurations.kakapo.config.system.build.toplevel
